import { signIn, useSession } from "next-auth/react";
import { useEffect } from "react";
import Head from "next/head";

import Sidebar from "@/components/sidebar";
import RecentPlayedList from "@/components/recent-played-list";

type MainLayoutProps = {
	children: React.ReactNode;
};

export default function MainLayout({ children }: MainLayoutProps) {
	const { data: session } = useSession();

	useEffect(() => {
		if (session?.error === "RefreshAccessTokenError") {
			signIn();
		}
	}, [session?.error]);

	return (
		<div className="min-h-screen">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex w-full min-h-screen">
				<Sidebar />

				<div className="flex flex-col bg-gradient-to-b from-slate-400 via-slate-500 to-slate-900 min-h-screen w-full">
					{children}
				</div>

				<RecentPlayedList />
			</div>
		</div>
	);
}
