import Head from "next/head";
import { useEffect } from "react";
import { signIn, useSession } from "next-auth/react";

import Sidebar from "@/components/sidebar";
import RecentPlayedList from "@/components/recent-played-list";
import Navbar from "@/components/navbar";
import Player from "@/components/player";
import Script from "next/script";

type MainLayoutProps = {
	children: React.ReactNode;
};

export default function MainLayout({ children }: MainLayoutProps) {
	const { data: session } = useSession();

	useEffect(() => {
		if (session?.error === "RefreshAccessTokenError") {
			signIn();
		}
	}, [session?.error]);

	return (
		<div className="min-h-screen">
			<Head>
				<title>Spotify Clone</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex w-full min-h-screen">
				<Sidebar />

				<div className="relative flex flex-col bg-gradient-to-b from-slate-400 via-zinc-900 to-slate-zinc-800 min-h-screen w-full">
					<Navbar />
					{children}

					<Player />
				</div>

				<RecentPlayedList />
			</div>
		</div>
	);
}
