import Head from "next/head";
import Sidebar from "@/components/sidebar";
import FriendActivity from "@/components/friend-activity";

type MainLayoutProps = {
	children: React.ReactNode;
};

export default function MainLayout({ children }: MainLayoutProps) {
	return (
		<div className="min-h-screen">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex w-full min-h-screen">
				<Sidebar />

				<div className="flex flex-col bg-gradient-to-b from-slate-400 via-slate-500 to-slate-900 min-h-screen w-full">
					{children}
				</div>

				<div className="flex flex-col bg-black w-[40%] h-screen text-gray-500 px-8 py-4">
					<h1>Friend Activity</h1>

					<div className="flex flex-col space-y-8 mt-4 w-full">
						<FriendActivity />
						<FriendActivity />
						<FriendActivity />
					</div>
				</div>
			</div>
		</div>
	);
}
